[packages]

[packages.siad]

path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siad/320317183d34fb5a735329a17048d5d9facc612a/datapackage.json"
token = "GITHUB_PAT"

[packages.siafi_2025]

path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2025/29e901ed2a02adde5811ddfac7bfd150ccd3c9f9/datapackage.json"
resources = ["execucao", "restos_pagar"]
token = "GITHUB_PAT"

[packages.siafi_2024]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2024/6090285b16f23de5e37e3b7016c6e2f008f07a12/datapackage.json"
resources = ["execucao", "restos_pagar"]
token = "GITHUB_PAT"

[packages.siafi_2023]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2023/1d6a467ed58e11cde2f57c816f9cb46d8a9451b5/datapackage.json"
resources = ["execucao", "restos_pagar"]
token = "GITHUB_PAT"

[packages.siafi_2022]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2022/89a09f6511f1460a0c08c52a2c1aa589713ab049/datapackage.json"
resources = ["execucao", "restos_pagar"]
token = "GITHUB_PAT"

[packages.siafi_2021]

path = "https://raw.githubusercontent.com/splor-mg/armazem-siafi-dados-2021/8b6dbfa40f8f38b0844c51155f6601522cc577e5/datapackage.json"
resources = ["execucao", "restos_pagar"]
token = "GITHUB_PAT"
